production:
  adapter: sqlserver
  mode: dblib
  dataserver:
  host: demox.database.windows.net
  port: 1433
  database: demox
  username: alejandro@demox
  password: Control5
  timeout: 5000
  azure: true

development:
  adapter: sqlserver
  mode: dblib
  dataserver:
  host: demox.database.windows.net
  port: 1433
  database: demox
  username: alejandro@demox
  password: Control5
  timeout: 5000
  azure: true
